# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter:         rouge
gems:                [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               James Gardiner
tagline:             'A blog for all things data'
description:         'A site for my analyses, findings, musings and other helpful stuff.'
url:                 jgardiner.co.uk
baseurl:             /
paginate:            5

# About/contact
author:
  name:              James Gardiner
  url:               https://twitter.com/James_G87
  email:             jamesg87@me.com
  github:            jamesGardiner
  twitter:           _JamesRG
  linkedin:          jrgardiner
  email_md5:         64efb4611c5f7a0f48d81a92c61e64e4

# Custom vars
version:             1.0.0
excerpt_separator:   "<!--more-->"
