# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter:         rouge
gems:                [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               James Gardiner
tagline:             'Another FOSS4G site'
description:         'A site about open source geospatial software - QGIS, PostGIS, Leaflet, OpenLayers and Python'
url:                 jamesgardiner.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              James Gardiner
  url:               https://twitter.com/James_G87
  email:             jamesg87@me.com
  github:            jamesGardiner
  twitter:           James_G87
  linkedin:          jrgardiner
  email_md5:         64efb4611c5f7a0f48d81a92c61e64e4

# Custom vars
version:             1.0.0
excerpt_separator:   "<!--more-->"
