# Site settings
title: James Gardiner
header-img: img/svalbard.jpg

email: jamesg87@me.com
copyright_name: James Gardiner
description: "A blog about data, analysis, and geography"
baseurl: ""
url: "http://jgardiner.co.uk"
twitter_username: _JamesRG
github_username:  JamesGardiner
linkedin_username:  jrgardiner
email_username:  jamesg87@me.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
