# Permalinks
permalink:        pretty
relative_permalinks: true

excerpt_separator: "<!-- more -->" # Adds read more feature

# Setup
title:            James Gardiner
tagline:          A blog about QGIS, Leaflet, OpenLayers and Python
url:              http://jamesgardiner.github.io
paginate:         1
baseurl:          /
author:
  name:           James Gardiner
  url:            https://twitter.com/
  email:          jamesg87@me.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/JamesGardiner/jamesgardiner.github.io
