# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               James Gardiner
tagline:             'A Blog about open source geo software - QGIS, Leaflet, OpenLayers and Python'
description:         'The personal blog of James Gardiner'
url:                 jamesgardiner.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              James Gardiner
  url:               https://twitter.com/James_G87
  email:             jamesg87@me.com

# Custom vars
version:             1.0.0
paginate:            5
excerpt_separator:   "<!--more-->"
